### ISSUE TITLE
Fps of TensorRT implementation

### ISSUE THREAD

**Issue by MaxLyubimov** [CarkusL/CenterPoint#2]
Hello, @CarkusL!  It's really interesting project and a lot of work has been done. I'm wondering what fps the resulting TensorRT model has. Have you evaluated the final FPS?

**Comment by CarkusL** [comment]
CUDA : 11.1
TensorRT : 7.2.2-1
GPU : RTX3090
Precision Mode: FP16
Max Pillar Number : 30000
Inupt  Shape: (1, 10, 30000, 20)
Average Inference Time(exclude preprocess and postprocess): 6.82434 ms

**Comment by MaxLyubimov** [comment]
Thank you for information !
