### ISSUE TITLE
Question When Parsing Bin File

### ISSUE THREAD

**Issue by mhmmdjafarg** [CarkusL/CenterPoint#24]
Hi i want to know why you set `constexpr int featureNum = 5;` when reading bin file? Is it because XYZI and what is the 5th?
 is it ringindex?
 do you have idea what to put in feature if the lidar dont provide ringindex?

Thank you

**Comment by CarkusL** [comment]
The 5th is time lag.
https://github.com/CarkusL/CenterPoint/blob/5912fab43dfe012112eb689a5a70d39c6bdf2654/tensorrt/samples/centerpoint/preprocess.cpp#L55C112-L55C112

When create dataset, we use 10 sweeps.
https://github.com/CarkusL/CenterPoint/blob/main/docs/NUSC.md
### nuScenes
```python tools/create_data.py nuscenes_data_prep --root_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --nsweeps=10```

**Comment by mhmmdjafarg** [comment]
Thanks!
