### ISSUE TITLE
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict

### ISSUE THREAD

**Issue by SCM00N** [CarkusL/CenterPoint#27]
hello everyone 

my dockerfile base "wowowoxuan/centerpoint:latest"

cuda : 10.0
torch : 1.1.0
torchvision : 0.3.0

training is very well.... 

But I try "python tools/export_pointpillars.py"  and 

ValueError: Unsupported ONNX opset version: 11

so I change
 
torch.onnx.export(pp_model, ((rpn_input)),"onnx_model/rpn.onnx",opset_version=10)

but " RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict "

main code opset_version=11 but torch=1.1.0 can't opset_version=11

so i try torch version up but spconv fail...

how can i do?

**Comment by CarkusL** [comment]
You can try to update pytorch to 1.9.0

**Comment by SCM00N** [comment]
if i try to update pytorch to 1.9.0

What CUDA version should I use?

cuda : 10.0 is fail :(
