### ISSUE TITLE
onnx result and torch result don't match

### ISSUE THREAD

**Issue by MengWangTHU** [CarkusL/CenterPoint#6]
Hi, Carkusl:
      thanks a lot for your work.
       I use the same tools and the same config to turn torch model to onnx model; I get pfe_onnx and rpn_onnx. Before simplify the onnx model,  I use onnxruntime to test the onnx result to validation if the reuslt consistent with the torch model. But I got the negative results. 
Wheather the pfe or the rpn,  the onnx inferenc results are very different with the torch results. 
I have not do the simplify. dose the simiplification work for the big difference of the model-inference-result?

Do you have any idea about the problem.

**Comment by CarkusL** [comment]
can you share your onnx models?

**Comment by MengWangTHU** [comment]
> I think the simplification doesn't affect the results.
> can you share your onnx models?

yeah, it's a pleasure to share my onnx models, incuding pfe and rpn. But how can i send them to you?

**Comment by MengWangTHU** [comment]
> > I think the simplification doesn't affect the results.
> > can you share your onnx models?
> 
> yeah, it's a pleasure to share my onnx models, incuding pfe and rpn. But how can i send them to you?

 Your email address?

**Comment by CarkusL** [comment]
> > > I think the simplification doesn't affect the results.
> > > can you share your onnx models?
> > 
> > 
> > yeah, it's a pleasure to share my onnx models, incuding pfe and rpn. But how can i send them to you?
> 
> Your email address?

you can upload your models to google drive
